FROM python:3.9-slim

RUN apt-get update && apt-get install -y \
    build-essential \
    gcc \
    librdkafka-dev

WORKDIR /app

COPY requirements.txt server.py data_pb2_grpc.py data_pb2.py data.proto /app/

RUN pip install -r requirements.txt 

CMD ["python", "server.py"]