# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: echo.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\necho.proto\x12\taisstream\"0\n\x07\x41ISData\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0c\n\x04long\x18\x03 \x01(\x01\"\x1c\n\x0b\x41ISResponse\x12\r\n\x05reply\x18\x01 \x01(\t2I\n\nAISService\x12;\n\x0bSendAisData\x12\x12.aisstream.AISData\x1a\x16.aisstream.AISResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'echo_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AISDATA']._serialized_start=25
  _globals['_AISDATA']._serialized_end=73
  _globals['_AISRESPONSE']._serialized_start=75
  _globals['_AISRESPONSE']._serialized_end=103
  _globals['_AISSERVICE']._serialized_start=105
  _globals['_AISSERVICE']._serialized_end=178
# @@protoc_insertion_point(module_scope)
